### ISSUE TITLE
How to use the from_position option?

### ISSUE THREAD

**Issue by warpdesign** [daniel-lundin/snabbt.js#15]
Is it possible to have from_position set to the previous end state by default without poking into CSS to get end state ?

**Comment by daniel-lundin** [comment]
If you chain animations it will do so automatically. Or if you start a new animation while another is running. In all other cases you have to store it yourself if you want to continue from where it ended. 

Reading from CSS is difficult since the transform is stored as a 4x4 matrix. 
Sorry if the documentation is unclear about this.

**Comment by warpdesign** [comment]
Thanks for your answer!

Documentation is a bit un clear, I thought `from_position: [0, 0, 0] or previous end state` meant you could specify something like 'end' so that snabbt automatically starts from previous end state.

The problem is if you don't chain your calls but want to move from previous state later on, there doesn't seem to be a way to do that other than poking into the matrix yourself.

**Comment by daniel-lundin** [comment]
I've been thinking about this, it would be really nice if the library could keep the end state of previous finished animations. That would make for a much more pleasant user(as in library user) experience.

The problem is in scenarios when DOM elements are added/removed dynamically. I need to figure out a way to listen for DOM detach events so that when elements are removed, their saved end state is removed as well. Otherwise the list of finished end states will just keep growing.

Maybe I can iterate through all finished animation when new ones are started.

I'll test out some different solutions and see if it can be accomplished.

**Comment by warpdesign** [comment]
Good thing you're working on it!

**Comment by daniel-lundin** [comment]
If you try the latest build from master it should work the way you want.
from_position will have precendence over previous end state, I think it makes most sense.
It will be out with the next release which should be really soon. I just want to get the memory optimization out at the same time.

If you find more issues with the from_-properties, please post here and I'll reopen it again.
