### ISSUE TITLE
CSS 'transfrom' state should be parsed as 'from'

### ISSUE THREAD

**Issue by bravedick** [daniel-lundin/snabbt.js#41]
We can get them from `window.getComputedStyle(element)['transform']`
Can we implement it or there is some troubles?

**Comment by bravedick** [comment]
The same with `opacity` and all CSS rules. We need to double now them: in JS from state and CSS

**Comment by daniel-lundin** [comment]
The opacity, width and height could be read parsed, but the transform cannot unfortunately.
The reason is that the transform is set on the element as a 4x4-matrix.
It's not possible to extract the separate transforms from it. Different sets of transform could result in the same matrix.

I don't want to put any DOM reading into snabbt, since it can cause performance problems.
