### ISSUE TITLE
setElementTransform is not count as 'fromPosition'

### ISSUE THREAD

**Issue by bravedick** [daniel-lundin/snabbt.js#58]
When i use `snabbt.setElementTransform` to set position for elements without animation (start position), and later set new position with snabbt, elements are animated from `0, 0`, but not from position, that was set in `snabbt.setElementTransform`.

Ask me for example if you can't reproduce or don't understand me.

**Comment by daniel-lundin** [comment]
I understand what you mean. 
However, the `setElementTransform`-function is very low-level since it takes a matrix as parameter. It's not possible to unambiguously extract position, rotation etc from that. 

For example, these two animation configurations would generate the same matrix:
```
{
   position: [200, 0, 0],
   rotationPost: [0,  0, Math.PI]
}
````
````
{
  position: [-200, 0, 0]
}
```

Have you tried using the snabbt()-call with a duration of 0 for just setting the position?
Haven't tried myself, but that would probably have the same effect.

**Comment by bravedick** [comment]
it worked for me only if duration was >= 1 and some 'blinking' was visible
so i needed to make element `visibility: hidden` and on callback return it to `visible`
it looks like some "hack", so i use `setElementTransform ` the same as `fromPosition`.
since it is not a bug, i close this issue. thank you for paying attention.
